implement actual installation phase

diff --git a/mp b/mp
--- a/mp
+++ b/mp
@@ -11,6 +11,16 @@ export LIB_COMMON="$MP_ROOT/lib/common"
 export LIB_INSTALLER="$MP_ROOT/lib/installer"
 export LIB_MISC="$MP_ROOT/lib/misc"
 
+if [[ -z "${INSTALL_DIR:-}" ]]; then
+    export INSTALL_DIR="${MP_ROOT%/*}"
+elif [[ "$INSTALL_DIR" != /* ]]; then
+    printf '[ERROR] INSTALL_DIR must be an absolute path: %s\n' "$INSTALL_DIR" >&2
+
+    exit 2
+else
+    export INSTALL_DIR
+fi
+
 main() {
     exec bash "$MP_COMMAND/main.sh" "$@"
 }
